agent:
  checked_exec_running: false
  config_name: ''
  display_name: SysMonager Agent
  exec_last_running: null
  service_name: SysMonagerAgent
  sysmon_version: ''
  uuid: 5bbc3427-a46f-490d-899b-7e9696757463
api:
  heartbeat: /heartbeat
  retry: 0
  updates:
    config: /updates/config
    sysmon: /updates/sysmon
sysmon:
  config_name: null
  installed: true
  version: null
testing:
  config_built: true
