agent:
  checked_exec_running: false
  config_name: ''
  display_name: SysMonager Agent
  exec_last_running: null
  service_name: SysMonagerAgent
  sysmon_version: ''
  uuid: af2674ba-6194-4e37-8c93-d6c345cdbf4c
api:
  heartbeat: /heartbeat
  retry: 0
  updates:
    config: /updates/config
    sysmon: /updates/sysmon
sysmon:
  config_name: null
  installed: true
  version: null
testing:
  config_built: true
