agent:
  checked_exec_running: false
  display_name: SysMonager Agent
  exec_last_running: null
  service_name: SysMonagerAgent
  uuid: e8420958-d255-48de-862c-7df07d3c4140
api:
  heartbeat: /heartbeat
  retry: 5
  updates:
    config: /updates/config
    sysmon: /updates/sysmon
sysmon:
  config_name: null
  installed: false
  version: null
testing:
  config_built: true
