agent:
  checked_exec_running: false
  config_name: null
  display_name: SysMonager Agent
  exec_last_running: null
  installed: false
  service_name: SysMonagerAgent
  sysmon_version: null
http:
  api:
    heartbeat: /heartbeat
    updates:
      config: /updates/config
      sysmon: /updates/sysmon
  uuid: null
