dist: xenial
language: minimal
matrix:
  include:
    - language: python
      python:
        - "3.7"
      dist: xenial
      before_install: cd server/backend
      install:
       - pip install -r requirements.txt
      script:
       - python manage.py test
      
    - language: node_js
      node_js:
        - "lts/*"
      before_install:
       - cd server/frontend
       - npm i -g @vue/cli
      script:
       - npm run lint
       - npm run test:unit
       - npm run build
notifications:
  email:
    - william.wernert@gmail.com
