dist: xenial
language: minimal
matrix:
  include:
    - language: python
      python:
        - "3.7"
      dist: xenial
      before_install: cd server/backend
      install:
        - pip install codecov
        - pip install coverage
        - pip install -r requirements.txt
      script:
        - coverage run --source='.' manage.py test
        - codecov
    - language: node_js
      node_js:
        - "lts/*"
      before_install:
        - cd server/frontend
        - npm i -g codecov
        - npm i -g @vue/cli
      script:
        - nyc --reporter=lcov --reporter=text-lcov npm run test:unit
        - codecov
    - language: minimal
      dist: xenial
      services: docker
      before_install:
        - docker build -t rwwiv/sysmonager .
        # - docker run -d -p 80:80 rwwiv/sysmonager
notifications:
  email:
    - william.wernert@gmail.com
