dist: xenial
language: minimal
matrix:
  include:
    - language: python
      python:
        - "3.7"
      dist: xenial
      before_install: cd server/backend
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test
    - language: python
      python:
        - "3.7"
      os: windows
      before_install: cd agent
      install:
        - pip install -r requirements.txt
      script:
        - python tests/test.py
    - language: node_js
      node_js:
        - "lts/*"
      before_install:
        - cd server/frontend
        - npm i -g @vue/cli
      script:
        - npm run lint
        - npm run test:unit
        - npm run build
    - language: minimal
      dist: xenial
      services: docker
      before_install:
        - docker build -t rwwiv/sysmonager .
        # - docker run -d -p 80:80 rwwiv/sysmonager
notifications:
  email:
    - william.wernert@gmail.com
