dist: xenial
language: minimal
matrix:
  include:
    - language: python
      python:
        - "3.7"
      dist: xenial
      before_install: cd server/backend
      install:
        - pip install codecov
        - pip install -r requirements.txt
      script:
        - python manage.py test
        - codecov
    - language: node_js
      node_js:
        - "lts/*"
      before_install:
        - cd server/frontend
      install:
        - npm i -g codecov
        - npm i -g @vue/cli
      script:
        - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
        - codecov
        - npm run test:unit
        - npm run build
    - language: minimal
      dist: xenial
      services: docker
      before_install:
        - docker build -t rwwiv/sysmonager .
        # - docker run -d -p 80:80 rwwiv/sysmonager
notifications:
  email:
    - william.wernert@gmail.com
