matrix:
  include:
    - language: python
      python:
        - "3.7"
      install:
       - pip install -r server/backend/requirements.txt
      script:
       - python server/backend/manage.py test
      
    - langauge: python
      python:
       - "3.7"
      install:
       - pip install -r agent/requirements.txt
      script:
       - python agent/tests/test.py
      
    - language: node_js
      node_js:
        - "lts"
      before_install:
       - npm i -g @vue/cli
      script:
       - npm run test
       - npm run build
notifications:
  email:
    - william.wernert@gmail.com