version: 0.1.{build}-{branch}
image: 
  - Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7.*"
      PYTHON_ARCH: "64"
install:
  - set "PATH=%PYTHON%;%PYTHON%/Scripts;%PYTHON%/Library/bin;%PATH%"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --set auto_update_conda no
  - conda install scipy geopandas xlrd netcdf4 h5py pytables matplotlib pytest pytest-mock pytest-cov pip m2w64-toolchain conda-build
  - python --version
  - cd agent
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
  - python -m pip install codecov
  - python -m pip install coverage
test_script:
  - python tests\test.py
  - coverage run tests\test.py
  - codecov
#build_script:
build: off
deploy: off
notifications:
  - provider: Email
    to:
      - william.wernert@gmail.com
    on_build_status_changed: true
