# Generated by Django 2.1.7 on 2019-04-20 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('UUID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('IP_ADDRESS', models.CharField(max_length=200)),
                ('ONLINE', models.BooleanField()),
                ('SYSMON_VERSION_CURRENT', models.CharField(max_length=200)),
                ('SYSMON_VERSION_NEW', models.CharField(max_length=200)),
                ('CONFIG_NAME_CURRENT', models.CharField(max_length=200)),
                ('CONFIG_NAME_NEW', models.CharField(max_length=200)),
                ('EXEC_LAST_RUNNING_AT', models.CharField(blank=True, max_length=200, null=True)),
                ('EXEC_RUNNING', models.BooleanField()),
                ('NEEDS_UNINSTALL', models.BooleanField()),
                ('NEEDS_RESTART', models.BooleanField()),
                ('NEEDS_INSTALL', models.BooleanField()),
                ('ATTEMPTED_INSTALL', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('NAME', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('IS_DEFAULT', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('NAME', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('CONFIGURATION', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Configuration')),
            ],
        ),
        migrations.CreateModel(
            name='Sysmon',
            fields=[
                ('VERSION', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('IS_CURRENT', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('PASSWORD', models.CharField(max_length=200)),
                ('LAST_LOGGED_IN', models.CharField(max_length=200)),
                ('LAST_LOGGED_OUT', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='SYSMON',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Sysmon'),
        ),
        migrations.AddField(
            model_name='agent',
            name='GROUP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Group'),
        ),
    ]
