# Generated by Django 2.1.7 on 2019-02-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=200)),
                ('IPV4_ADDRESS', models.CharField(max_length=200)),
                ('IPV6_ADDRESS', models.CharField(max_length=200)),
                ('ONLINE', models.BooleanField()),
                ('SYSMON_VERSION_CURRENT', models.CharField(max_length=200)),
                ('SYSMON_VERSION_NEW', models.CharField(max_length=200)),
                ('CONFIG_NAME_CURRENT', models.CharField(max_length=200)),
                ('CONFIG_NAME_NEW', models.CharField(max_length=200)),
                ('EXEC_RUNNING', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.CharField(max_length=200)),
                ('PASSWORD', models.CharField(max_length=200)),
                ('LAST_LOGGED_IN', models.CharField(max_length=200)),
                ('LAST_LOGGED_OUT', models.CharField(max_length=200)),
            ],
        ),
    ]
