# Generated by Django 2.1.7 on 2019-02-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=200)),
                ('IS_DEFAULT', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='NEEDS_RESTART',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='NEEDS_UNINSTALL',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
