# Generated by Django 2.1.7 on 2019-02-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0003_agent_exec_last_running_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='NEEDS_INSTALL',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
