# Generated by Django 2.1.7 on 2019-02-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0004_agent_needs_install'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sysmon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=200)),
                ('IS_CURRENT', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='IPV4_ADDRESS',
            new_name='IP_ADDRESS',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='IPV6_ADDRESS',
        ),
    ]
