# Generated by Django 2.1.7 on 2019-03-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0005_auto_20190228_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='ATTEMPTED_INSTALL',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
