# Generated by Django 2.1.7 on 2019-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0006_agent_attempted_install'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='EXEC_LAST_RUNNING_AT',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
