# Generated by Django 2.1.7 on 2019-04-10 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0007_auto_20190305_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('NAME', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sysmon',
            name='NAME',
        ),
        migrations.RemoveField(
            model_name='sysmon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='sysmon',
            name='VERSION',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='UUID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='NAME',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='USER_ID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='group',
            name='CONFIGURATION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbeat.Configuration'),
        ),
        migrations.AddField(
            model_name='group',
            name='SYSMON',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbeat.Sysmon'),
        ),
        migrations.AddField(
            model_name='agent',
            name='GROUP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbeat.Group'),
        ),
    ]
