# Generated by Django 2.1.7 on 2019-04-18 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0008_auto_20190410_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='CONFIGURATION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbeat.Configuration'),
        ),
    ]
