# Generated by Django 2.1.7 on 2019-04-19 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0010_auto_20190418_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='UUID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='CONFIGURATION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbeat.Configuration'),
        ),
    ]
