# Generated by Django 2.1.7 on 2019-04-19 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0013_auto_20190419_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='id',
        ),
        migrations.AlterField(
            model_name='agent',
            name='UUID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='CONFIGURATION',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='heartbeat.Configuration'),
        ),
    ]
