# Generated by Django 2.1.7 on 2019-04-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0014_auto_20190419_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='GROUP',
        ),
        migrations.RemoveField(
            model_name='group',
            name='CONFIGURATION',
        ),
        migrations.RemoveField(
            model_name='group',
            name='SYSMON',
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.DeleteModel(
            name='agent',
        ),
        migrations.DeleteModel(
            name='configuration',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Sysmon',
        ),
    ]
